# HIE Opt-Out Guide - GitHub Pages Configuration

# Site URL for GitHub Pages
url: "https://thefonze74065.github.io"
baseurl: "/hie-opt-out"

# Build settings for GitHub Pages
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files from the build
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
  - .gitignore
  - .github/

# Site metadata
title: "HIE Opt-Out Guide"
description: "Protect your health information privacy - Learn how to opt out of Health Information Exchange sharing"
author: "HIE Opt-Out Guide Contributors"

# Google Analytics (uncomment and add your GA tracking ID if desired)
# google_analytics: UA-XXXXXXXX-X

# Social metadata for better sharing
social:
  type: "website"
  title: "HIE Opt-Out Guide"
  description: "A comprehensive guide to opting out of Health Information Exchange sharing"
  url: "https://thefonze74065.github.io/hie-opt-out/"
